input.onButtonPressed(Button.A, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    magicbit.Servospeed(magicbit.Servos.S1, 60, 100, 4)
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    magicbit.Servospeed(magicbit.Servos.S2, 40, 120, 5)
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    magicbit.Servospeed(magicbit.Servos.S3, 60, 20, 5)
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    magicbit.Servospeed(magicbit.Servos.S8, 50, 30, 4)
    basic.pause(500)
    magicbit.Servospeed(magicbit.Servos.S8, 30, 50, 4)
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    magicbit.Servospeed(magicbit.Servos.S3, 20, 60, 5)
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    magicbit.Servospeed(magicbit.Servos.S2, 120, 40, 4)
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    magicbit.Servospeed(magicbit.Servos.S1, 100, 60, 4)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(5000)
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P16, 4, NeoPixelMode.RGB)
basic.showIcon(IconNames.Happy)
magicbit.Servo(magicbit.Servos.S1, 60)
magicbit.Servo(magicbit.Servos.S2, 40)
magicbit.Servo(magicbit.Servos.S3, 60)
magicbit.Servo(magicbit.Servos.S8, 50)
